on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: 'print current location'
         run: pwd
       - name: 'make list'
         run: ls
       - name: 'print my name'
         run: echo "said ahmed"

