on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
 
       - name: 'print current location' 
         run: pwd
       - name: "login to docker hub" 
         run: docker login --username ${{ secrets.DOCKER_RSERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
